"""
Family-safe content screening for the pipeline.

Every story generated by generate_script.py is screened before it is
accepted: the hook, title, scene narration, and visual keywords are checked
against a prohibited-terms list (profanity, obscenity, sexual content,
nudity references, gore, drugs - in English and Hindi). Anything flagged is
regenerated with the offending terms fed back as forbidden, so no vulgar
text ever reaches the voiceover, subtitles, or image prompts.

Matching is deliberately broad: whole words AND common inflected forms
(plurals like "bitches"/"whores", derived forms like "masturbation") and
masked variants (f*ck, s3x, b1tch). The list errs on the side of caution:
a false positive just costs one regeneration, a miss would publish
inappropriate content on YouTube.

The safety wall is always enabled. It cannot be disabled through an environment variable.
"""
import os
import re

_ENABLED = True  # hard safety wall: never disabled in production

# Unambiguous terms, matched as whole words - so "classic", "assess",
# "assist" are NOT flagged even though they contain letters of "ass".
PROHIBITED = [
    # profanity / vulgarity
    "asshole", "bastard", "bitch", "bullshit", "crap", "cunt", "damn",
    "dammit", "dick", "douchebag", "fuck", "fucked", "fucker", "fucking",
    "jackass", "motherfucker", "piss", "pissed", "pussy", "shit", "shitty",
    "slut", "twat", "whore", "wanker", "bollocks", "hooker",
    # sexual content / nudity references
    # ("bare" and "oral" are deliberately excluded: "bare rock" and "oral
    # traditions" are common in space/mythology stories and are innocent)
    "anal", "blowjob", "boob", "boobs", "bottomless", "breast",
    "buttocks", "erotic", "escort", "explicit", "fetish", "genital",
    "handjob", "incest", "intercourse", "kink", "lingerie",
    "molest", "naked", "nipple", "nude", "nudity", "orgasm", "orgy",
    "panties", "pedophile", "penetration", "penis", "porn", "pornography",
    "provocative", "racy", "rape", "seductive", "semen",
    "sensual", "sex", "sexual", "sexy", "smut", "sperm", "stripper",
    "striptease", "pornographic", "seduction", "seductive", "horny", "lewd",
    "stripping", "tits", "topless", "vagina", "underwear",
    # gore / drugs / self-harm (YouTube-hostile)
    "cocaine", "gore", "guts", "heroin", "meth",
    "methamphetamine", "suicide", "severed",
    # common Hindi profanity
    "bhenchod", "behenchod", "bhosdi", "bhosdike", "chut", "chutiya",
    "gand", "gandu", "harami", "kutta", "kutti", "lund", "maderchod",
    "madarchod", "raand", "randi", "sala", "sali",
    # common Devanagari safety terms
    "नग्न", "नग्नता", "नंगा", "नंगी", "अश्लील", "कामुक", "यौन",
    "सेक्स", "पोर्न", "बलात्कार", "भद्दा", "अशोभनीय",
]


# Stems matched as word-prefixes so derived forms are caught too:
# masturbation, masturbating, decapitated, mutilation, tortured, etc.
# Each entry is (readable label, stem) - the label is what gets reported.
STEMS = [
    ("decapitation", "decapitat"),
    ("masturbation", "masturbat"),
    ("mutilation", "mutilat"),
    ("prostitution", "prostitut"),
    ("torture", "tortur"),
]

# Obfuscated variants (l33t / masked letters) that plain matching would
# miss: f*ck, sh1t, s3x, b1tch, n4ked, a**hole, etc. Each entry is
# (readable label, compiled regex) - the label is what gets reported.
_PATTERNS = [
    # Each character class includes `*` so literal masked forms like "f*ck"
    # and "b*tch" are caught - LLMs self-censor with asterisks exactly when
    # drifting toward profanity.
    ("f*ck", re.compile(r"\bf[u*]+ck(?:ing|er|ed|ers|s)?\b", re.IGNORECASE)),
    ("sh*t", re.compile(r"\bsh[i1!*]+t(?:s)?\b", re.IGNORECASE)),
    ("s*x", re.compile(r"\bs[e3*]+x(?:y|ual|es)?\b", re.IGNORECASE)),
    ("a**hole", re.compile(r"\b[a@*]+sshole(?:s)?\b", re.IGNORECASE)),
    ("b*tch", re.compile(r"\bb[i1!*]+tch(?:es)?\b", re.IGNORECASE)),
    ("n*ked", re.compile(r"\bn[a@4*]+ked\b", re.IGNORECASE)),
    ("n*de", re.compile(r"\bn[u*][d*][e3*]s?\b", re.IGNORECASE)),
    ("porn", re.compile(r"\bporn(?:ography|os)?\b", re.IGNORECASE)),
    ("d*ck", re.compile(r"\bd[i1!*]+ck(?:s)?\b", re.IGNORECASE)),
    ("p*ssy", re.compile(r"\bp[u*]+ss(?:y|ies)\b", re.IGNORECASE)),
    ("c*nt", re.compile(r"\bc[u*]+nt(?:s)?\b", re.IGNORECASE)),
    ("wh*re", re.compile(r"\bwh[o0*]+re(?:s)?\b", re.IGNORECASE)),
    ("motherf*cker", re.compile(r"\bm[o0]+therf[o0*]+ck(?:er|ers)?\b", re.IGNORECASE)),
    ("rape", re.compile(r"\brap(?:e|ing|es|ed|s)\b", re.IGNORECASE)),
    # fully-masked forms where the letters are replaced by asterisks
    # entirely (f**k, s**t, b**ch, a**hole, n**de):
    ("f**k", re.compile(r"\bf\*{1,3}k\b", re.IGNORECASE)),
    ("sh**t", re.compile(r"\bs\*{1,3}t\b", re.IGNORECASE)),
    ("b**ch", re.compile(r"\bb\*{1,3}ch\b", re.IGNORECASE)),
    ("d**k", re.compile(r"\bd\*{1,3}k\b", re.IGNORECASE)),
    ("a**hole", re.compile(r"\ba\*{1,3}hole\b", re.IGNORECASE)),
    ("n**de", re.compile(r"\bn\*{1,3}de\b", re.IGNORECASE)),
]


def _inflections(word):
    """The word plus its common plural forms, for whole-word matching
    (so "bitches" flags "bitch", "pussies" flags "pussy", etc.)."""
    forms = {word}
    if word.endswith(("s", "x", "z", "ch", "sh")):
        forms.add(word + "es")
    elif (word.endswith("y") and len(word) > 1
            and not word.endswith(("ay", "ey", "oy", "uy"))):
        forms.add(word[:-1] + "ies")
    forms.add(word + "s")
    return forms


def find_prohibited(text):
    """Return the sorted list of prohibited terms found in text ([] if clean)."""
    if not _ENABLED or not text:
        return []
    lowered = text.lower()
    found = set()
    for term in PROHIBITED:
        for form in _inflections(term):
            if re.search(rf"\b{re.escape(form)}\b", lowered):
                found.add(term)
                break
    for label, stem in STEMS:
        if re.search(rf"\b{re.escape(stem)}", lowered):
            found.add(label)
    for label, pattern in _PATTERNS:
        if pattern.search(text):
            found.add(label)
    return sorted(found)
